export const REQUEST_HIGH_SCORES_START = 'REQUEST_HIGH_SCORES_START';
export const REQUEST_HIGH_SCORES_FINISH = 'GET_HIGH_SCORES_FINISH';
export const RECEIVE_HIGH_SCORES = 'RECEIVE_HIGH_SCORES';

export const SWITCH_SECTION = 'SWITCH_SECTION';

export const START_GAME = 'START_GAME';
export const FINISH_GAME = 'FINISH_GAME';
export const GAME_TICK = 'GAME_TICK';
export const GAME_CORRECT_ANSWER = 'GAME_CORRECT_ANSWER';
export const GAME_WRONG_ANSWER = 'GAME_WRONG_ANSWER';
export const GAME_CAN_SHARE = 'GAME_CAN_SHARE';